[package]
name = "comma"
version = "0.26.2"
edition = "2024"

[dependencies]
ureq = { version = "3", default-features = false, features = ["rustls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
crossterm = "0.28"
rustyline = "15"
rust-i18n = "3"

[profile.release]
strip = true
opt-level = "z"
lto = true
panic = "abort"
codegen-units = 1
